#!/bin/bash

TMPDIR=`mktemp -d`
INSTALL_DIR=/gg

trap "rm -rf \"$TMPDIR\"" exit


make clean
autoconf
./configure --host=ppc-morphos --with-curl=/gg/usr --with-openssl=/gg/ssl --prefix=$INSTALL_DIR --with-expat=/gg/usr
make MORPHOS=1 "DESTDIR=$TMPDIR" install -j4
find "$TMPDIR" -name '*::*' | xargs rm -rf
find "$TMPDIR" | xargs file | grep 'PowerPC' | awk '{print substr($1, 1, length($1)-1)}' | xargs ppc-morphos-strip --strip-unneeded --remove-section=.comment

rm -rf "$TMPDIR$INSTALLDIR/lib"

tar -cJf ./git-morphos-2.17.0.tar.xz -C "$TMPDIR/gg" ./


